apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-runner

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - externalsecret.yaml
  - ecr-secret.yaml
