apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/
  - external-secrets/
  - kong/
  - services/ms-product/
  - services/ms-inventory/
  - services/ms-supplier/
  - services/ms-order-management/
  - services/ms-identity/
  - services/frontend/
  - istio/
