apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-autoscaler

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - podmonitor.yaml

commonLabels:
  app.kubernetes.io/name: cluster-autoscaler
  app.kubernetes.io/component: autoscaler
  app.kubernetes.io/part-of: infrastructure
