apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - rbac-kube-system.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cluster-autoscaler
      app.kubernetes.io/component: autoscaler
      app.kubernetes.io/part-of: infrastructure
    includeSelectors: false
